### PR TITLE
Pr branch

### PR DESCRIPTION
**Pull request by n3n7i**
Hi, like to try again? Idk if you'd rather pull to a non-master branch to start with, edits enabled

So, there's a second style implemented in ScrollTables.css, accessed with `TableOptions(BrowseTables.DEFAULTCSSDIR*"\\ScrollTables.css", true)` - defaults to unmodified css
Schema patch for tables that pass @argcheck, also used as a redirect for single tables - coax it to display the thead labels
Multitables -nonbreaking, passed as [table, table] - combines with the .divstyle display:inline block setting of Scrolltables.css

Todo: delete /* th & td consistency */ bits, check code +comments still apply, test schema_patch some more - other table types?
Future: modular css?

### CODE REVIEW

**Comment by tpapp** [comment]
Thanks. I am very busy now, will only be able to look at this next week.

**Comment by n3n7i** [comment]
You're welcome, and that's fine i'll just leave this open. 
There is quite a bit of scope creep, and as a note I think just `thead{ position: sticky; top:0px; }` might possibly be all that was needed as per request & discussion

**Comment by n3n7i** [comment]
There's a bit of a neat trick on the experimental branch
`line 105: show(pretty, content);`
So anytime a usertype emits html with `show()` we can include that in the table unescaped

**Comment by n3n7i** [comment]
I think we can close this one too, it's mostly redundant
Can always recycle a few bits if you ever want multiple tables

**Comment by tpapp** [comment]
Thanks. I appreciate that you extracted #7 from this PR, which fixed the original issue.

**Pull request closed without merging**
